version: '3.8'
services:
  postgres:
    image: postgres:16.2
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DBNAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER}", "-d", "${PG_DBNAME}" ]
      interval: 1s
      timeout: 1s
      retries: 60
    restart: always
    networks:
      - my_network
    extra_hosts:
      - "localhost:host-gateway"
  flask:
    build: .
    env_file: .env
    environment:
      - DEBUG_MODE=false
    ports:
      - ${FLASK_PORT}:5000
    stop_signal: SIGINT
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_network
    extra_hosts:
      - "localhost:host-gateway"
networks:
  my_network: