"""empty message

Revision ID: b4e7ebe86c8b
Revises: 
Create Date: 2024-05-21 22:11:24.922371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e7ebe86c8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('length(name) < 80 and length(country) < 80 and length(logo) < 500'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country', name='league_unique_name_country')
    )
    op.create_table('stadiums',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('capacity > 0', name='capacity_positive'),
    sa.CheckConstraint('length(address) < 150 and length(city) < 80'),
    sa.CheckConstraint('length(name) < 80 and length(image) < 500'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', name='stadium_unique_name_address')
    )
    op.create_table('teams',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('founded', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('stadium_id', sa.Uuid(), nullable=True),
    sa.Column('league_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("founded <= (date_part('year', now()))", name='founded_not_future'),
    sa.CheckConstraint('length(name) < 80 and length(logo) < 500'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'founded', name='team_unique_name_founded')
    )
    op.create_table('players',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('length(name) < 80 and length(position) < 40 and length(photo) < 500'),
    sa.CheckConstraint('number > 0 and age > 0', name='number_age_positive'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'age', 'number', name='player_unique_name_age_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('teams')
    op.drop_table('stadiums')
    op.drop_table('leagues')
    # ### end Alembic commands ###
